theme: jekyll-theme-minimal
title: "CyberCypher Blog"
description: "Exploring the world of cybersecurity."
show_downloads: false

# Enable Jekyll Blog System
plugins:
  - jekyll-feed

# Ensure future-dated posts are displayed
future: true

# Fix duplicate 'future' setting

permalink: /blog/:title.html

exclude:
  - .jekyll-cache
  - _site

baseurl: "/cyber-blog"
